package eu.factorx.awac.util;

public enum BusinessErrorType {

	INVALID_PASSWORD,
	INVALID_IDENTIFIER,
	INVALID_IDENTIFIER_ALREADY_USED,
	INVALID_ORGANIZATION_NAME_ALREADY_USED,
	INVALID_IDENTIFIER_BAD_INTERFACE,
	INVALID_MUNICIPALITY_NAME_ALREADY_USED,
	ACCESS_UNAUTHORIZED,
	ACCESS_NOT_ADMIN,
	ACCESS_NOT_SYSTEM_ADMIN

	}
