define [
  "./awac/mmAwacBlock/directive"
  "./awac/mmAwacBooleanQuestion/directive"
  "./awac/mmAwacDocumentQuestion/directive"
  "./awac/mmAwacEnterpriseSurvey/directive"
  "./awac/mmAwacIntegerQuestion/directive"
  "./awac/mmAwacModalConfirmationExitForm/directive"
  "./awac/mmAwacModalDocumentManager/directive"
  "./awac/mmAwacModalFieldText/directive"
  "./awac/mmAwacModalLoading/directive"
  "./awac/mmAwacModalLogin/directive"
  "./awac/mmAwacPercentageQuestion/directive"
  "./awac/mmAwacQuestion/directive"
  "./awac/mmAwacRealQuestion/directive"
  "./awac/mmAwacRealWithUnitQuestion/directive"
  "./awac/mmAwacRepetitionName/directive"
  "./awac/mmAwacRepetitionQuestion/directive"
  "./awac/mmAwacRepetitionQuestionDisabled/directive"
  "./awac/mmAwacSection/directive"
  "./awac/mmAwacSelectQuestion/directive"
  "./awac/mmAwacStringQuestion/directive"
  "./awac/mmAwacSubSubTitle/directive"
  "./awac/mmAwacTabProgressBar/directive"
  "./awac/mmEnter/directive"
  "./awac/mmPercent/directive"
  "./myrmex/mmNotImplemented/directive"
], ->