package eu.factorx.awac.service.knowledge.activity.contributor.event;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import eu.factorx.awac.models.code.conversion.ConversionCriterion;
import eu.factorx.awac.models.code.type.*;
import eu.factorx.awac.models.data.answer.QuestionAnswer;
import eu.factorx.awac.models.data.answer.QuestionSetAnswer;
import eu.factorx.awac.models.knowledge.Unit;
import eu.factorx.awac.models.reporting.BaseActivityData;
import eu.factorx.awac.service.knowledge.activity.contributor.ActivityResultContributor;
import org.springframework.stereotype.Component;

/**
* AUTO-GENERATED by BADImportator at 10/12/2014 08:56
* Name of the BAD : mobilité avion des visiteurs
 */
@Component
public class BaseActivityDataAEV_BAD5 extends ActivityResultContributor {

    @Override
    public List<BaseActivityData> getBaseActivityData(Map<QuestionCode, List<QuestionSetAnswer>> questionSetAnswers) {

        List<BaseActivityData> res = new ArrayList<>();

        //1. build unit(s) needed for
        //  - a) the BAD.unit
        //  - b) conversion

        // Get Target Unit (GJ in this case)
        // Allow finding unit by a UnitCode (unit symbole = passagers.km )
        Unit baseActivityDataUnit = getUnitByCode(UnitCode.U5328);


        //2. build BAD

        
        //2.1 loop for each answer for each loop for each parents of one or more question needed by the BAD
        
            
                            List<QuestionSetAnswer> questionSetAnswersAEV58 = questionSetAnswers.get(QuestionCode.AEV58);
                //2.2 control if the list if different than null
                if (questionSetAnswersAEV58 == null) {
                    return res;
                }
            
            //loop ($repetition.mainQuestionSetDescription)
                            for (QuestionSetAnswer questionSetAnswer1 : questionSetAnswersAEV58) {
             
                            //create a map for each repetition level
                Map<QuestionCode, QuestionAnswer> answersByCode1 = byQuestionCode(questionSetAnswer1.getQuestionAnswers());

                //load question for this level
                                    QuestionAnswer questionAEV59Answer = answersByCode1.get(QuestionCode.AEV59);
                                    QuestionAnswer questionAEV61Answer = answersByCode1.get(QuestionCode.AEV61);
                                    QuestionAnswer questionAEV60Answer = answersByCode1.get(QuestionCode.AEV60);
                                    QuestionAnswer questionAEV63Answer = answersByCode1.get(QuestionCode.AEV63);
                                    QuestionAnswer questionAEV62Answer = answersByCode1.get(QuestionCode.AEV62);
                
                    //control them
                    if (                            questionAEV59Answer == null  ||
                                                                                questionAEV61Answer == null  ||
                                                                                questionAEV60Answer == null  ||
                                                                                questionAEV63Answer == null  ||
                                                                                questionAEV62Answer == null                                                 ) {
                       continue;
                    }
                    
            
            //build the bad
            BaseActivityData baseActivityData = new BaseActivityData();

            baseActivityData.setKey(BaseActivityDataCode.AEV_BAD5);
                            baseActivityData.setAlternativeGroup("null");
                        baseActivityData.setRank(0);
            baseActivityData.setSpecificPurpose(toString(questionAEV59Answer));
            baseActivityData.setActivityCategory(ActivityCategoryCode.AC_5);
            baseActivityData.setActivitySubCategory(ActivitySubCategoryCode.ASC_9);
            baseActivityData.setActivityType(toActivityTypeCode(questionAEV61Answer));

            baseActivityData.setActivitySource(toActivitySourceCode(questionAEV60Answer));

            baseActivityData.setActivityOwnership(false);
            baseActivityData.setUnit(baseActivityDataUnit);
            baseActivityData.setValue(toDouble(questionAEV63Answer, getUnitByCode(UnitCode.U5106))*toDouble(questionAEV62Answer));
            res.add(baseActivityData);

            
                         }
                 return res;
    }

}