package eu.factorx.awac.service.knowledge.activity.contributor.impl;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import eu.factorx.awac.models.code.type.*;
import eu.factorx.awac.models.data.answer.QuestionAnswer;
import eu.factorx.awac.models.data.answer.QuestionSetAnswer;
import eu.factorx.awac.models.knowledge.Unit;
import eu.factorx.awac.models.reporting.BaseActivityData;
import eu.factorx.awac.service.knowledge.activity.contributor.ActivityResultContributor;
import org.springframework.stereotype.Component;

/**
* AUTO-GENERATED by BADImportator at 15/09/2014 12:52
* Name of the BAD : Site: Déchet eau industrielle directe
 */
@Component
public class BaseActivityDataAE_BAD25 extends ActivityResultContributor {

    @Override
    public List<BaseActivityData> getBaseActivityData(Map<QuestionCode, List<QuestionSetAnswer>> questionSetAnswers) {

        List<BaseActivityData> res = new ArrayList<>();

        //1. build unit(s) needed for
        //  - a) the BAD.unit
        //  - b) conversion

        // Get Target Unit (GJ in this case)
        // Allow finding unit by a UnitCode (unit symbole = m3 )
        Unit baseActivityDataUnit = getUnitByCode(UnitCode.U5122);


        //2. build BAD

        
        //2.1 loop for each answer for each loop for each parents of one or more question needed by the BAD
        
            
                            List<QuestionSetAnswer> questionSetAnswersA197 = questionSetAnswers.get(QuestionCode.A197);
                //2.2 control if the list if different than null
                if (questionSetAnswersA197 == null) {
                    return res;
                }
            
            //loop ($repetition.mainQuestionSetDescription)
                            for (QuestionSetAnswer questionSetAnswer1 : questionSetAnswersA197) {
             
                            //create a map for each repetition level
                Map<QuestionCode, QuestionAnswer> answersByCode1 = byQuestionCode(questionSetAnswer1.getQuestionAnswers());

                //load question for this level
                                    QuestionAnswer questionA200Answer = answersByCode1.get(QuestionCode.A200);
                                    QuestionAnswer questionA198Answer = answersByCode1.get(QuestionCode.A198);
                                    QuestionAnswer questionA195Answer = answersByCode1.get(QuestionCode.A195);
                                    QuestionAnswer questionA199Answer = answersByCode1.get(QuestionCode.A199);
                
                    //control them
                    if (                            questionA200Answer == null  ||
                                                                                questionA198Answer == null  ||
                                                                                questionA195Answer == null  ||
                                                                                questionA199Answer == null                                                 ) {
                       continue;
                    }
                    
            
            //build the bad
            BaseActivityData baseActivityData = new BaseActivityData();

            baseActivityData.setKey(BaseActivityDataCode.AE_BAD25);
            baseActivityData.setRank(1);
            baseActivityData.setSpecificPurpose(null);
            baseActivityData.setActivityCategory(ActivityCategoryCode.AC_7);
            baseActivityData.setActivitySubCategory(ActivitySubCategoryCode.ASC_10);
            baseActivityData.setActivityType(toActivityTypeCode(questionA200Answer));

            baseActivityData.setActivitySource(toActivitySourceCode(questionA198Answer));

            baseActivityData.setActivityOwnership(getCode(questionA195Answer).getKey().equals("1"));
            baseActivityData.setUnit(baseActivityDataUnit);
            baseActivityData.setValue(toDouble(questionA199Answer, getUnitByCode(UnitCode.U5122)));
            res.add(baseActivityData);

            
                         }
                 return res;
    }

}