package eu.factorx.awac.service.knowledge.activity.contributor.household;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import eu.factorx.awac.models.code.conversion.ConversionCriterion;
import eu.factorx.awac.models.code.type.*;
import eu.factorx.awac.models.data.answer.QuestionAnswer;
import eu.factorx.awac.models.data.answer.QuestionSetAnswer;
import eu.factorx.awac.models.knowledge.Unit;
import eu.factorx.awac.models.reporting.BaseActivityData;
import eu.factorx.awac.service.knowledge.activity.contributor.ActivityResultContributor;
import org.springframework.stereotype.Component;

/**
* AUTO-GENERATED by BADImportator at 09/12/2014 04:55
* Name of the BAD : mobilité avion
 */
@Component
public class BaseActivityDataAM_BAD9 extends ActivityResultContributor {

    @Override
    public List<BaseActivityData> getBaseActivityData(Map<QuestionCode, List<QuestionSetAnswer>> questionSetAnswers) {

        List<BaseActivityData> res = new ArrayList<>();

        //1. build unit(s) needed for
        //  - a) the BAD.unit
        //  - b) conversion

        // Get Target Unit (GJ in this case)
        // Allow finding unit by a UnitCode (unit symbole = passagers.km )
        Unit baseActivityDataUnit = getUnitByCode(UnitCode.U5328);


        //2. build BAD

        
        //2.1 loop for each answer for each loop for each parents of one or more question needed by the BAD
        
            
                            List<QuestionSetAnswer> questionSetAnswersAM134 = questionSetAnswers.get(QuestionCode.AM134);
                //2.2 control if the list if different than null
                if (questionSetAnswersAM134 == null) {
                    return res;
                }
            
            //loop ($repetition.mainQuestionSetDescription)
                            for (QuestionSetAnswer questionSetAnswer1 : questionSetAnswersAM134) {
             
                            //create a map for each repetition level
                Map<QuestionCode, QuestionAnswer> answersByCode1 = byQuestionCode(questionSetAnswer1.getQuestionAnswers());

                //load question for this level
                                    QuestionAnswer questionAM135Answer = answersByCode1.get(QuestionCode.AM135);
                                    QuestionAnswer questionAM137Answer = answersByCode1.get(QuestionCode.AM137);
                                    QuestionAnswer questionAM136Answer = answersByCode1.get(QuestionCode.AM136);
                                    QuestionAnswer questionAM138Answer = answersByCode1.get(QuestionCode.AM138);
                                    QuestionAnswer questionAM139Answer = answersByCode1.get(QuestionCode.AM139);
                
                    //control them
                    if (                            questionAM135Answer == null  ||
                                                                                questionAM137Answer == null  ||
                                                                                questionAM136Answer == null  ||
                                                                                questionAM138Answer == null  ||
                                                                                questionAM139Answer == null                                                 ) {
                       continue;
                    }
                    
            
            //build the bad
            BaseActivityData baseActivityData = new BaseActivityData();

            baseActivityData.setKey(BaseActivityDataCode.AM_BAD9);
                            baseActivityData.setAlternativeGroup("null");
                        baseActivityData.setRank(0);
            baseActivityData.setSpecificPurpose(toString(questionAM135Answer));
            baseActivityData.setActivityCategory(ActivityCategoryCode.AC_5);
            baseActivityData.setActivitySubCategory(ActivitySubCategoryCode.ASC_17);
            baseActivityData.setActivityType(toActivityTypeCode(questionAM137Answer));

            baseActivityData.setActivitySource(toActivitySourceCode(questionAM136Answer));

            baseActivityData.setActivityOwnership(false);
            baseActivityData.setUnit(baseActivityDataUnit);
            baseActivityData.setValue(toDouble(questionAM138Answer)*toDouble(questionAM139Answer, getUnitByCode(UnitCode.U5106)));
            res.add(baseActivityData);

            
                         }
                 return res;
    }

}