package eu.factorx.awac.models.code.type;

import eu.factorx.awac.models.code.Code;
import eu.factorx.awac.models.code.CodeList;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.Embeddable;

@Embeddable
@AttributeOverrides({@AttributeOverride(name = "key", column = @Column(name = "secteursecondaire"))})
public class SECTEURSECONDAIRECode extends Code {

	public static final SECTEURSECONDAIRECode _10_INDUSTRIES_ALIMENTAIRES = new SECTEURSECONDAIRECode("1");
	public static final SECTEURSECONDAIRECode _11_FABRICATION_DE_BOISSONS = new SECTEURSECONDAIRECode("2");
	public static final SECTEURSECONDAIRECode _12_FABRICATION_DE_PRODUITS_A_BASE_DE_TABAC = new SECTEURSECONDAIRECode("3");
	public static final SECTEURSECONDAIRECode _13_FABRICATION_DE_TEXTILES = new SECTEURSECONDAIRECode("4");
	public static final SECTEURSECONDAIRECode _14_INDUSTRIE_DE_L_HABILLEMENT = new SECTEURSECONDAIRECode("5");
	public static final SECTEURSECONDAIRECode _15_INDUSTRIE_DU_CUIR_ET_DE_LA_CHAUSSURE = new SECTEURSECONDAIRECode("6");
	public static final SECTEURSECONDAIRECode _16_TRAVAIL_DU_BOIS_ET_FABRICATION_D_ARTICLES_EN_BOIS_ET_EN_LIEGE_A_L_EXCEPTION_DES_MEUBLES_FABRICATION_D_ARTICLES_EN_VANNERIE_ET_SPARTERIE = new SECTEURSECONDAIRECode("7");
	public static final SECTEURSECONDAIRECode _17_INDUSTRIE_DU_PAPIER_ET_DU_CARTON = new SECTEURSECONDAIRECode("8");
	public static final SECTEURSECONDAIRECode _18_IMPRIMERIE_ET_REPRODUCTION_D_ENREGISTREMENTS = new SECTEURSECONDAIRECode("9");
	public static final SECTEURSECONDAIRECode _19_COKEFACTION_ET_RAFFINAGE = new SECTEURSECONDAIRECode("10");
	public static final SECTEURSECONDAIRECode _20_INDUSTRIE_CHIMIQUE = new SECTEURSECONDAIRECode("11");
	public static final SECTEURSECONDAIRECode _21_INDUSTRIE_PHARMACEUTIQUE = new SECTEURSECONDAIRECode("12");
	public static final SECTEURSECONDAIRECode _22_FABRICATION_DE_PRODUITS_EN_CAOUTCHOUC_ET_EN_PLASTIQUE = new SECTEURSECONDAIRECode("13");
	public static final SECTEURSECONDAIRECode _23_FABRICATION_D_AUTRES_PRODUITS_MINERAUX_NON_METALLIQUES = new SECTEURSECONDAIRECode("14");
	public static final SECTEURSECONDAIRECode _24_METALLURGIE = new SECTEURSECONDAIRECode("15");
	public static final SECTEURSECONDAIRECode _25_FABRICATION_DE_PRODUITS_METALLIQUES_A_L_EXCEPTION_DES_MACHINES_ET_DES_EQUIPEMENTS = new SECTEURSECONDAIRECode("16");
	public static final SECTEURSECONDAIRECode _26_FABRICATION_DE_PRODUITS_INFORMATIQUES_ELECTRONIQUES_ET_OPTIQUES = new SECTEURSECONDAIRECode("17");
	public static final SECTEURSECONDAIRECode _27_FABRICATION_D_EQUIPEMENTS_ELECTRIQUES = new SECTEURSECONDAIRECode("18");
	public static final SECTEURSECONDAIRECode _28_FABRICATION_DE_MACHINES_ET_D_EQUIPEMENTS_N_C_A = new SECTEURSECONDAIRECode("19");
	public static final SECTEURSECONDAIRECode _29_CONSTRUCTION_ET_ASSEMBLAGE_DE_VEHICULES_AUTOMOBILES_DE_REMORQUES_ET_DE_SEMI_REMORQUES = new SECTEURSECONDAIRECode("20");
	public static final SECTEURSECONDAIRECode _30_FABRICATION_D_AUTRES_MATERIELS_DE_TRANSPORT = new SECTEURSECONDAIRECode("21");
	public static final SECTEURSECONDAIRECode _31_FABRICATION_DE_MEUBLES = new SECTEURSECONDAIRECode("22");
	public static final SECTEURSECONDAIRECode _32_AUTRES_INDUSTRIES_MANUFACTURIERES = new SECTEURSECONDAIRECode("23");
	public static final SECTEURSECONDAIRECode _33_REPARATION_ET_INSTALLATION_DE_MACHINES_ET_D_EQUIPEMENTS = new SECTEURSECONDAIRECode("24");
	public static final SECTEURSECONDAIRECode _35_PRODUCTION_ET_DISTRIBUTION_D_ELECTRICITE_DE_GAZ_DE_VAPEUR_ET_D_AIR_CONDITIONNE = new SECTEURSECONDAIRECode("25");
	private static final long serialVersionUID = 1L;
	protected SECTEURSECONDAIRECode() {
		super(CodeList.SECTEURSECONDAIRE);
	}
	public SECTEURSECONDAIRECode(String key) {
		this();
		this.key = key;
	}
}