package eu.factorx.awac.models.code.type;

import eu.factorx.awac.models.code.Code;
import eu.factorx.awac.models.code.CodeList;

public class SECTEURTERTIAIRECode extends Code {

	private static final long serialVersionUID = 1L;

	protected SECTEURTERTIAIRECode() {
		super(CodeList.SECTEURTERTIAIRE);
	}

	public SECTEURTERTIAIRECode(String key) {
		this();
		this.key = key;
	}
/*
    public static final SECTEURTERTIAIRECode 36_CAPTAGE_TRAITEMENT_ET_DISTRIBUTION_D_EAU=new

    SECTEURTERTIAIRECode("1");

    public static final SECTEURTERTIAIRECode 37_COLLECTE_ET_TRAITEMENT_DES_EAUX_USEES=new

    SECTEURTERTIAIRECode("2");

    public static final SECTEURTERTIAIRECode 38_COLLECTE_TRAITEMENT_ET_ELIMINATION_DES_DECHETS_RECUPERATION=new

    SECTEURTERTIAIRECode("3");

    public static final SECTEURTERTIAIRECode 39_DEPOLLUTION_ET_AUTRES_SERVICES_DE_GESTION_DES_DECHETS=new

    SECTEURTERTIAIRECode("4");

    public static final SECTEURTERTIAIRECode 41_CONSTRUCTION_DE_BATIMENTS_PROMOTION_IMMOBILIERE=new

    SECTEURTERTIAIRECode("5");

    public static final SECTEURTERTIAIRECode 42_GENIE_CIVIL=new

    SECTEURTERTIAIRECode("6");

    public static final SECTEURTERTIAIRECode 43_TRAVAUX_DE_CONSTRUCTION_SPECIALISES=new

    SECTEURTERTIAIRECode("7");

    public static final SECTEURTERTIAIRECode 45_COMMERCE_DE_GROS_ET_DE_DETAIL_ET_REPARATION_VEHICULES_AUTOMOBILES_ET_DE_MOTOCYCLES=new

    SECTEURTERTIAIRECode("8");

    public static final SECTEURTERTIAIRECode 46_COMMERCE_DE_GROS_A_L_EXCEPTION_DES_VEHICULES_AUTOMOBILES_ET_DES_MOTOCYCLES=new

    SECTEURTERTIAIRECode("9");

    public static final SECTEURTERTIAIRECode 47_COMMERCE_DE_DETAIL_A_L_EXCEPTION_DES_VEHICULES_AUTOMOBILES_ET_DES_MOTOCYCLES=new

    SECTEURTERTIAIRECode("10");

    public static final SECTEURTERTIAIRECode 49_TRANSPORTS_TERRESTRES_ET_TRANSPORT_PAR_CONDUITES=new

    SECTEURTERTIAIRECode("11");

    public static final SECTEURTERTIAIRECode 50_TRANSPORTS_PAR_EAU=new

    SECTEURTERTIAIRECode("12");

    public static final SECTEURTERTIAIRECode 51_TRANSPORTS_AERIENS=new

    SECTEURTERTIAIRECode("13");

    public static final SECTEURTERTIAIRECode 52_ENTREPOSAGE_ET_SERVICES_AUXILIAIRES_DES_TRANSPORTS=new

    SECTEURTERTIAIRECode("14");

    public static final SECTEURTERTIAIRECode 53_ACTIVITES_DE_POSTE_ET_DE_COURRIER=new

    SECTEURTERTIAIRECode("15");

    public static final SECTEURTERTIAIRECode 55_HEBERGEMENT=new

    SECTEURTERTIAIRECode("16");

    public static final SECTEURTERTIAIRECode 56_RESTAURATION=new

    SECTEURTERTIAIRECode("17");

    public static final SECTEURTERTIAIRECode 58_EDITION=new

    SECTEURTERTIAIRECode("18");

    public static final SECTEURTERTIAIRECode 59_PRODUCTION_DE_FILMS_CINEMATOGRAPHIQUES_DE_VIDEO_ET_DE_PROGRAMMES_DE_TELEVISION_ENREGISTREMENT_SONORE_ET_EDITION_MUSICALE=new

    SECTEURTERTIAIRECode("19");

    public static final SECTEURTERTIAIRECode 60_PROGRAMMATION_ET_DIFFUSION_DE_PROGRAMMES_DE_RADIO_ET_DE_TELEVISION=new

    SECTEURTERTIAIRECode("20");

    public static final SECTEURTERTIAIRECode 61_TELECOMMUNICATIONS=new

    SECTEURTERTIAIRECode("21");

    public static final SECTEURTERTIAIRECode 62_PROGRAMMATION_CONSEIL_ET_AUTRES_ACTIVITES_INFORMATIQUES=new

    SECTEURTERTIAIRECode("22");

    public static final SECTEURTERTIAIRECode 63_SERVICES_D_INFORMATION=new

    SECTEURTERTIAIRECode("23");

    public static final SECTEURTERTIAIRECode 64_ACTIVITES_DES_SERVICES_FINANCIERS_HORS_ASSURANCE_ET_CAISSES_DE_RETRAITE=new

    SECTEURTERTIAIRECode("24");

    public static final SECTEURTERTIAIRECode 65_ASSURANCE_REASSURANCE_ET_CAISSES_DE_RETRAITE_A_L_EXCLUSION_DES_ASSURANCES_SOCIALES_OBLIGATOIRES=new

    SECTEURTERTIAIRECode("25");

    public static final SECTEURTERTIAIRECode 66_ACTIVITES_AUXILIAIRES_DE_SERVICES_FINANCIERS_ET_D_ASSURANCE=new

    SECTEURTERTIAIRECode("26");

    public static final SECTEURTERTIAIRECode 68_ACTIVITES_IMMOBILIERES=new

    SECTEURTERTIAIRECode("27");

    public static final SECTEURTERTIAIRECode 69_ACTIVITES_JURIDIQUES_ET_COMPTABLES=new

    SECTEURTERTIAIRECode("28");

    public static final SECTEURTERTIAIRECode 70_ACTIVITES_DES_SIEGES_SOCIAUX_CONSEIL_DE_GESTION=new

    SECTEURTERTIAIRECode("29");

    public static final SECTEURTERTIAIRECode 71_ACTIVITES_D_ARCHITECTURE_ET_D_INGENIERIE_ACTIVITES_DE_CONTROLE_ET_ANALYSES_TECHNIQUES=new

    SECTEURTERTIAIRECode("30");

    public static final SECTEURTERTIAIRECode 72_RECHERCHE_DEVELOPPEMENT_SCIENTIFIQUE=new

    SECTEURTERTIAIRECode("31");

    public static final SECTEURTERTIAIRECode 73_PUBLICITE_ET_ETUDES_DE_MARCHE=new

    SECTEURTERTIAIRECode("32");

    public static final SECTEURTERTIAIRECode 74_AUTRES_ACTIVITES_SPECIALISEES_SCIENTIFIQUES_ET_TECHNIQUES=new

    SECTEURTERTIAIRECode("33");

    public static final SECTEURTERTIAIRECode 75_ACTIVITES_VETERINAIRES=new

    SECTEURTERTIAIRECode("34");

    public static final SECTEURTERTIAIRECode 77_ACTIVITES_DE_LOCATION_ET_LOCATION_BAIL=new

    SECTEURTERTIAIRECode("35");

    public static final SECTEURTERTIAIRECode 78_ACTIVITES_LIEES_A_L_EMPLOI=new

    SECTEURTERTIAIRECode("36");

    public static final SECTEURTERTIAIRECode 79_ACTIVITES_DES_AGENCES_DE_VOYAGE_VOYAGISTES_SERVICES_DE_RESERVATION_ET_ACTIVITES_CONNEXES=new

    SECTEURTERTIAIRECode("37");

    public static final SECTEURTERTIAIRECode 80_ENQUETES_ET_SECURITE=new

    SECTEURTERTIAIRECode("38");

    public static final SECTEURTERTIAIRECode 81_SERVICES_RELATIFS_AUX_BATIMENTS_AMENAGEMENT_PAYSAGER=new

    SECTEURTERTIAIRECode("39");

    public static final SECTEURTERTIAIRECode 82_SERVICES_ADMINISTRATIFS_DE_BUREAU_ET_AUTRES_ACTIVITES_DE_SOUTIEN_AUX_ENTREPRISES=new

    SECTEURTERTIAIRECode("40");

    public static final SECTEURTERTIAIRECode 84_ADMINISTRATION_PUBLIQUE_ET_DEFENSE_M5SECURITE_SOCIALE_OBLIGATOIRE=new

    SECTEURTERTIAIRECode("41");

    public static final SECTEURTERTIAIRECode 85_ENSEIGNEMENT=new

    SECTEURTERTIAIRECode("42");

    public static final SECTEURTERTIAIRECode 86_ACTIVITES_POUR_LA_SANTE_HUMAINE=new

    SECTEURTERTIAIRECode("43");

    public static final SECTEURTERTIAIRECode 87_ACTIVITES_MEDICO_SOCIALES_ET_SOCIALES_AVEC_HEBERGEMENT=new

    SECTEURTERTIAIRECode("44");

    public static final SECTEURTERTIAIRECode 88_ACTION_SOCIALE_SANS_HEBERGEMENT=new

    SECTEURTERTIAIRECode("45");

    public static final SECTEURTERTIAIRECode 90_ACTIVITES_CREATIVES_ARTISTIQUES_ET_DE_SPECTACLE=new

    SECTEURTERTIAIRECode("46");

    public static final SECTEURTERTIAIRECode 91_BIBLIOTHEQUES_ARCHIVES_MUSEES_ET_AUTRES_ACTIVITES_CULTURELLES=new

    SECTEURTERTIAIRECode("47");

    public static final SECTEURTERTIAIRECode 92_ORGANISATION_DE_JEUX_DE_HASARD_ET_D_ARGENT=new

    SECTEURTERTIAIRECode("48");

    public static final SECTEURTERTIAIRECode 93_ACTIVITES_SPORTIVES_RECREATIVES_ET_DE_LOISIRS=new

    SECTEURTERTIAIRECode("49");

    public static final SECTEURTERTIAIRECode 94_ACTIVITES_DES_ORGANISATIONS_ASSOCIATIVES=new

    SECTEURTERTIAIRECode("50");

    public static final SECTEURTERTIAIRECode 95_REPARATION_D_ORDINATEURS_ET_DE_BIENS_PERSONNELS_ET_DOMESTIQUES=new

    SECTEURTERTIAIRECode("51");

    public static final SECTEURTERTIAIRECode 96_AUTRES_SERVICES_PERSONNELS=new

    SECTEURTERTIAIRECode("52");

    public static final SECTEURTERTIAIRECode 97_ACTIVITES_DES_MENAGES_EN_TANT_QU_EMPLOYEURS_DE_PERSONNEL_DOMESTIQUE=new

    SECTEURTERTIAIRECode("53");

    public static final SECTEURTERTIAIRECode 98_ACTIVITES_INDIFFERENCIEES_DES_MENAGES_EN_TANT_QUE_PRODUCTEURS_DE_BIENS_ET_SERVICES_POUR_USAGE_PROPRE=new

    SECTEURTERTIAIRECode("54");

    public static final SECTEURTERTIAIRECode 99_ACTIVITES_DES_ORGANISATIONS_ET_ORGANISMES_EXTRATERRITORIAUX=new

    SECTEURTERTIAIRECode("55");*/
}