package eu.factorx.awac.models.code;

public enum CodeList {

    LANGUAGE,
    GENDER,
    HEATING_FUEL_TYPE,
    SCOPE_TYPE,
    QUESTION,
    INDICATOR_SCOPE,
    SITE_SECTORS,
    PUBLIC_PRIVATE,
    NACE_CODES_1,
    NACE_CODES_2,
    NACE_CODES_3,
    FUEL,
    INDICATOR_TYPE,
    INDICATOR_CATEGORY,
    INDICATOR_ISO_SCOPE,
    ACTIVITY_CATEGORY,
    ACTIVITY_SUB_CATEGORY,
    ACTIVITY_TYPE,
    ACTIVITY_SOURCE,
    UNIT

}
