package eu.factorx.awac.models.code;

public enum CodeList {

	LANGUAGE,
	GENDER,
	HEATING_FUEL_TYPE,
	SCOPE_TYPE,
	QUESTION,
	INDICATOR_SCOPE,
	SITE_SECTOR,
	INDICATOR_TYPE,
	INDICATOR_CATEGORY,
	INDICATOR_ISO_SCOPE,
	ACTIVITY_CATEGORY,
	ACTIVITY_SUB_CATEGORY,
	ACTIVITY_TYPE,
	ACTIVITY_SOURCE;

}
